import { Injectable } from '@angular/core';
import { Title, Meta } from '@angular/platform-browser';

/**
 * SEO service for dynamically updating page title and meta tags.
 * Uses Angular's Title and Meta services for SSR-compatible metadata.
 */
@Injectable({
  providedIn: 'root',
})
export class SeoService {
  private readonly baseTitle = 'CareerCompass AI';
  private readonly baseDescription =
    'AI-powered career guidance and skill verification platform. Get your technical skills verified and receive a personalized career roadmap.';

  constructor(private title: Title, private meta: Meta) {}

  /** Set metadata for the chat page. */
  updateForChat(): void {
    this.title.setTitle(`${this.baseTitle} — AI Career Counselor`);
    this.updateMeta(
      'Chat with our AI Career Counselor to discover your ideal tech career path. Get personalized skill verification and career roadmaps.'
    );
  }

  /** Set metadata for the dashboard page. */
  updateForDashboard(career?: string): void {
    const careerStr = career || 'Tech';
    this.title.setTitle(
      `${careerStr} Skill Dashboard — ${this.baseTitle}`
    );
    this.updateMeta(
      `View your verified ${careerStr} skill scores and gap analysis. Track your progress towards becoming a ${careerStr} professional.`
    );
  }

  /** Set metadata for the roadmap view. */
  updateForRoadmap(career?: string): void {
    const careerStr = career || 'Tech';
    this.title.setTitle(
      `${careerStr} Career Roadmap — ${this.baseTitle}`
    );
    this.updateMeta(
      `Your personalized ${careerStr} career roadmap with curated resources, milestones, and timelines. Generated by AI based on your verified skill profile.`
    );
    this.meta.updateTag({
      property: 'og:title',
      content: `${careerStr} Career Roadmap — ${this.baseTitle}`,
    });
  }

  /** Reset to default metadata. */
  resetToDefault(): void {
    this.title.setTitle(
      `${this.baseTitle} — AI-Powered Career Guidance & Skill Verification`
    );
    this.updateMeta(this.baseDescription);
  }

  private updateMeta(description: string): void {
    this.meta.updateTag({ name: 'description', content: description });
    this.meta.updateTag({
      property: 'og:description',
      content: description,
    });
  }
}
